"""Update property and related models

Revision ID: dbc73c8bb3f7
Revises: 7c73b55a1c35
Create Date: 2025-07-08 20:46:52.040714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbc73c8bb3f7'
down_revision: Union[str, None] = '7c73b55a1c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subleases_sublease_id'), table_name='subleases')
    op.drop_table('subleases')
    op.drop_index(op.f('ix_user_ratings_rating_id'), table_name='user_ratings')
    op.drop_table('user_ratings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ratings',
    sa.Column('rating_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sublease_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rater_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rated_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rated_user_id'], ['users.user_id'], name=op.f('user_ratings_rated_user_id_fkey')),
    sa.ForeignKeyConstraint(['rater_id'], ['users.user_id'], name=op.f('user_ratings_rater_id_fkey')),
    sa.ForeignKeyConstraint(['sublease_id'], ['subleases.sublease_id'], name=op.f('user_ratings_sublease_id_fkey')),
    sa.PrimaryKeyConstraint('rating_id', name=op.f('user_ratings_pkey'))
    )
    op.create_index(op.f('ix_user_ratings_rating_id'), 'user_ratings', ['rating_id'], unique=False)
    op.create_table('subleases',
    sa.Column('sublease_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lessor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('minimum_stay_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('maximum_stay_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('available_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('available_until', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lessor_id'], ['users.user_id'], name=op.f('subleases_lessor_id_fkey')),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], name=op.f('subleases_property_id_fkey')),
    sa.PrimaryKeyConstraint('sublease_id', name=op.f('subleases_pkey'))
    )
    op.create_index(op.f('ix_subleases_sublease_id'), 'subleases', ['sublease_id'], unique=False)
    # ### end Alembic commands ###
